import { mkdir, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { CV_TEMPLATE_CAPABILITIES } from '@/shared/constants/cv-template-capabilities';
import { planCvBuildSpec } from '@/shared/services/cv-build-spec';
import { prioritizeCvContent } from '@/shared/services/cv-content-priority';
import { renderCvDocx } from '@/shared/services/cv-generation';
import {
  structuredRewriteToRewrittenData,
  validateStructuredRewriteProvenance,
} from '@/shared/services/cv-rewrite-structured';
import {
  GOLDEN_CONTRACT_LIMITATIONS,
  GOLDEN_COVERAGE_RATIONALE,
  GOLDEN_CV_FIXTURES,
  goldenOutputFilename,
} from './fixtures';
import { validateGoldenDocx } from './docx-validator';
import type { GoldenManifest, GoldenManifestEntry } from './types';

export const GOLDEN_OUTPUT_DIRECTORY = path.join('artifacts', 'golden-cvs');

function relativeArtifactPath(fileName: string): string {
  return path.posix.join('artifacts', 'golden-cvs', fileName);
}

function reviewMarkdown(manifest: GoldenManifest): string {
  const minimalIds = new Set([
    'administration-sparse-source-architect',
    'registered-nurse-normal-approved-editorial_refined',
    'software-engineering-dense-mixed-technical_precision',
    'frontline-operations-multipage-application-academic_latex',
    'healthcare-support-normal-source-architect',
    'it-support-dense-general-editorial_refined',
    'general-normal-edge-cases-technical_precision',
    'software-engineering-dense-mixed-academic_latex',
  ]);
  const minimal = manifest.entries.filter((entry) => minimalIds.has(entry.fixtureId));
  const lines = [
    '# Stage 4 Golden CV Review',
    '',
    'Generated by `npm run generate:golden-cvs`. Automated results are structural and evidence-safety checks, not subjective human approval.',
    '',
    '## Minimal human-review set',
    '',
    ...minimal.map((entry) => `- [ ] ${entry.outputPath} — ${entry.occupation}; ${entry.density}; ${entry.template}`),
    '',
    'This set covers all four templates, sparse, dense, likely multi-page, technical, regulated healthcare, administration/operations, mixed approved/application evidence, malformed-link handling and General-profile fallback.',
    '',
    '## Pagination and visual checks that remain human-owned',
    '',
    '- Confirm no clipped or overlapping text in Microsoft Word and the browser download flow.',
    '- Check orphaned headings, isolated bullets, nearly blank spill pages and excessive blank bands.',
    '- Check tables, date alignment, hyperlink wrapping, font substitution and content behind shapes/columns.',
    '- Confirm the visual identity of each template remains distinct without content changes.',
    '',
    '## Fixture reviews',
    '',
  ];

  for (const entry of manifest.entries) {
    const fixture = GOLDEN_CV_FIXTURES.find((candidate) => candidate.fixtureId === entry.fixtureId)!;
    lines.push(
      `### ${entry.fixtureId}`,
      '',
      `- DOCX: ${entry.outputPath}`,
      `- Purpose: ${entry.purpose}`,
      `- Occupation: ${entry.occupation}`,
      `- Density / template: ${entry.density} / ${entry.template}`,
      `- Evidence sources: ${entry.evidenceSources.join(', ')}`,
      `- Expected page tendency: ${entry.expectedPageTendency}`,
      `- Actual rendered page count: ${entry.automatedCheck.pageCount ?? 'not rendered yet'}`,
      `- Expected section order: ${entry.expectedSectionOrder.join(' → ')}`,
      `- Important claims: ${entry.expectedClaims.join(' | ')}`,
      `- Forbidden claims: ${entry.forbiddenClaims.join(' | ')}`,
      `- Links: ${entry.expectedLinks.join(' | ') || 'none'}`,
      `- Dates: ${entry.expectedDateStrings.join(' | ') || 'none'}`,
      `- Known visual risks: ${fixture.expected.knownVisualRisks.join(' | ')}`,
      `- Automated result: ${entry.automatedCheck.passed ? 'AUTOMATED PASS — HUMAN REVIEW REQUIRED' : 'AUTOMATED FAIL'}`,
      `- Detected issues: ${entry.automatedCheck.errors.join(' | ') || 'none'}`,
      `- Rendered PDF/images: ${entry.renderedPdfPath ?? 'not rendered'} / ${entry.renderedImagePaths.join(', ') || 'not rendered'}`,
      '- Human result: [ ] PASS  [ ] PASS WITH FIXES  [ ] FAIL',
      '- Human notes:',
      '',
      '  ____________________________________________________________________________',
      ''
    );
  }
  return `${lines.join('\n')}\n`;
}

export async function generateGoldenCvArtifacts(workspaceRoot = process.cwd()): Promise<GoldenManifest> {
  const outputDirectory = path.join(workspaceRoot, GOLDEN_OUTPUT_DIRECTORY);
  // The directory is wholly managed, ignored and reproducible. Clearing it
  // prevents stale DOCX/PDF names from contaminating a later review pack.
  await rm(outputDirectory, { recursive: true, force: true });
  await mkdir(outputDirectory, { recursive: true });
  const entries: GoldenManifestEntry[] = [];

  for (const fixture of GOLDEN_CV_FIXTURES) {
    const provenance = validateStructuredRewriteProvenance(
      fixture.structuredRewrite,
      fixture.generationInput
    );
    if (!provenance.ok) {
      throw new Error(`${fixture.fixtureId}: invalid fixture provenance: ${provenance.reasons.join(' | ')}`);
    }
    const adapted = structuredRewriteToRewrittenData(
      fixture.structuredRewrite,
      CV_TEMPLATE_CAPABILITIES[fixture.template].summaryMaxChars
    );
    const contentPlan = prioritizeCvContent({
      data: adapted.data,
      claimSourceRefs: adapted.claimSourceRefs,
      requirements: fixture.generationInput.rewriteContext.requirements,
      pageLengthExpectation: CV_TEMPLATE_CAPABILITIES[fixture.template].pageLengthExpectation,
    });
    const spec = planCvBuildSpec({
      data: contentPlan.data,
      templateId: fixture.template,
      occupationId: fixture.occupation,
      role: fixture.targetRole,
      targetSource: 'stage4_fixture',
      contentPlan,
    });
    if (JSON.stringify(spec.provenance.sectionOrder) !== JSON.stringify(fixture.expected.sectionOrder)) {
      throw new Error(`${fixture.fixtureId}: canonical section order changed.`);
    }
    if (spec.presentation.densityMode !== fixture.expected.densityMode) {
      throw new Error(`${fixture.fixtureId}: density mode changed from ${fixture.expected.densityMode} to ${spec.presentation.densityMode}.`);
    }

    const buffer = await renderCvDocx(spec);
    const fileName = goldenOutputFilename(fixture);
    await writeFile(path.join(outputDirectory, fileName), buffer);
    const automatedCheck = await validateGoldenDocx(buffer, fixture);
    entries.push({
      fixtureId: fixture.fixtureId,
      fixtureVersion: fixture.fixtureVersion,
      purpose: fixture.purpose,
      occupation: fixture.occupationLabel,
      density: fixture.density,
      template: fixture.template,
      evidenceSources: fixture.evidenceSources,
      expectedSectionOrder: fixture.expected.sectionOrder,
      expectedHeadings: fixture.expected.headings,
      expectedDensityMode: fixture.expected.densityMode,
      expectedClaims: fixture.expected.claims,
      forbiddenClaims: fixture.expected.forbiddenClaims,
      expectedLinks: fixture.expected.links,
      expectedDateStrings: fixture.expected.dateStrings,
      expectedPageTendency: fixture.expected.pageTendency,
      expectedProvenanceSources: fixture.expected.provenanceSources,
      outputPath: relativeArtifactPath(fileName),
      renderedPdfPath: null,
      renderedImagePaths: [],
      automatedCheck,
      humanResult: null,
      humanNotes: null,
    });
  }

  const manifest: GoldenManifest = {
    schemaVersion: 1,
    fixtureVersion: 'v1',
    generatedBy: 'npm run generate:golden-cvs',
    entries,
    coverageRationale: GOLDEN_COVERAGE_RATIONALE,
    contractLimitations: GOLDEN_CONTRACT_LIMITATIONS,
  };
  const json = `${JSON.stringify(manifest, null, 2)}\n`;
  await Promise.all([
    writeFile(path.join(outputDirectory, 'manifest.json'), json, 'utf8'),
    writeFile(path.join(outputDirectory, 'AUTOMATED_RESULTS.json'), json, 'utf8'),
    writeFile(path.join(outputDirectory, 'REVIEW.md'), reviewMarkdown(manifest), 'utf8'),
  ]);
  return manifest;
}
