// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL first, DATABASE_URL as the fallback.
    //
    // This config drives the Prisma CLI only — the app connects through the
    // adapter in src/shared/lib/prisma.ts, which always uses DATABASE_URL.
    // The split matters against Neon: DATABASE_URL points at the PgBouncer
    // pooler, which does not reliably support the advisory locks and DDL that
    // Migrate needs. Setting DIRECT_URL to the unpooled endpoint (the same
    // host without `-pooler`) makes migrations work without the app losing
    // pooling. Locally there is no pooler, so DIRECT_URL can simply be unset.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
