import React from 'react';
import { Cpu, Sparkles } from 'lucide-react';
import { cn } from '@/shared/utils/cn';

/**
 * Where a card's finding comes from:
 *  - 'rule'   deterministic — the same input always yields the same result.
 *  - 'ai'     generated by the language model; a judgement, not a fixed fact.
 *  - 'hybrid' rule-based signal enriched by the AI layer.
 */
export type AnalysisSource = 'rule' | 'ai' | 'hybrid';

const CONFIG: Record<AnalysisSource, { label: string; icon: typeof Cpu; classes: string }> = {
  rule: {
    label: 'Rule-based',
    icon: Cpu,
    classes: 'bg-slate-100 text-slate-500 border-slate-200/70',
  },
  ai: {
    label: 'AI-generated',
    icon: Sparkles,
    classes: 'bg-accent-purple/10 text-accent-purple border-accent-purple/20',
  },
  hybrid: {
    label: 'AI + rules',
    icon: Sparkles,
    classes: 'bg-accent-purple/5 text-accent-purple/90 border-accent-purple/15',
  },
};

export default function SourceBadge({
  source,
  className,
}: {
  source: AnalysisSource;
  className?: string;
}) {
  const { label, icon: Icon, classes } = CONFIG[source];
  return (
    <span
      className={cn(
        'inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] font-bold uppercase tracking-wide',
        classes,
        className
      )}
    >
      <Icon size={10} strokeWidth={2.5} />
      {label}
    </span>
  );
}
