'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams } from 'next/navigation';
import { ExternalLink, MapPin } from 'lucide-react';
import Navbar from '@/shared/components/layout/Navbar';
import Button from '@/shared/components/ui/Button';
import JobMatchPreparation from './JobMatchPreparation';

type Details = { snapshot: { id: string; title: string; employerName: string; locationText?: string | null; workStyle?: string | null; salaryText?: string | null; contractType?: string | null; employmentType?: string | null; providerDescription?: string | null; userSuppliedDescription?: string | null; descriptionAvailability: 'FULL' | 'PARTIAL' | 'EXTERNAL_ONLY'; providerReferences: { provider: string; providerUrl: string }[] }; profiles: { profileId: string; label: string; isDefault?: boolean }[]; selectedProfile: { profileId: string; label: string } | null; usage: { used?: number; limit?: number; remaining?: number; period?: string } | null };
export default function JobDetailsClient() {
  const { jobSnapshotId } = useParams<{ jobSnapshotId: string }>();
  const [data, setData] = useState<Details | null>(null); const [error, setError] = useState(''); const [matchOpen, setMatchOpen] = useState(false);
  useEffect(() => { fetch(`/api/jobs/${encodeURIComponent(jobSnapshotId)}`).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? 'Unable to load this vacancy.'); return body; }).then(setData).catch((caught) => setError(caught instanceof Error ? caught.message : 'Unable to load this vacancy.')); }, [jobSnapshotId]);
  if (error) return <main className="min-h-screen bg-hero-gradient"><Navbar /><div className="mx-auto max-w-3xl px-4 pt-28 text-error">{error} <Link href="/jobs" className="underline">Return to Job Board</Link></div></main>;
  if (!data) return <main className="min-h-screen bg-hero-gradient"><Navbar /><div className="mx-auto max-w-3xl px-4 pt-28 text-text-secondary">Loading vacancy…</div></main>;
  const { snapshot } = data; const description = snapshot.userSuppliedDescription ?? snapshot.providerDescription; const meta = [snapshot.workStyle?.toLowerCase(), snapshot.salaryText, snapshot.contractType, snapshot.employmentType].filter(Boolean).join(' · '); const originalUrl = snapshot.providerReferences[0]?.providerUrl;
  return <main className="min-h-screen bg-hero-gradient pb-12"><Navbar /><section className="mx-auto max-w-4xl px-4 pb-12 pt-28"><Link href="/jobs" className="text-sm text-accent-purple hover:underline">← Back to Job Board</Link><article className="mt-4 rounded-2xl border border-border-subtle bg-bg-primary p-5 sm:p-8"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs text-text-tertiary">Source: {snapshot.providerReferences.map((reference) => reference.provider).join(' · ')}</p><h1 className="mt-1 text-2xl font-bold text-text-primary sm:text-3xl">{snapshot.title}</h1><p className="mt-1 text-text-secondary">{snapshot.employerName} · <span className="inline-flex items-center gap-1"><MapPin size={14} />{snapshot.locationText}</span></p>{meta && <p className="mt-3 text-sm text-text-secondary">{meta}</p>}</div><Button type="button" onClick={() => setMatchOpen(true)}>Check match</Button></div><div className="mt-6 flex flex-wrap gap-2 text-xs">{snapshot.descriptionAvailability === 'FULL' ? <span className="rounded-full bg-success/10 px-3 py-1 text-success">Full provider description available</span> : <span className="rounded-full bg-warning/10 px-3 py-1 text-warning">Partial provider description</span>}{snapshot.userSuppliedDescription && <span className="rounded-full bg-bg-tertiary px-3 py-1">User-supplied description selected</span>}</div><div className="mt-7 border-t border-border-subtle pt-6"><h2 className="text-lg font-semibold text-text-primary">Job description</h2><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-text-secondary">{description || 'The provider did not make a description available.'}</p></div>{originalUrl && <div className="mt-7 flex gap-3"><a href={originalUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-sm text-accent-purple hover:underline">Open original listing <ExternalLink size={14} /></a></div>}</article></section>{matchOpen && <JobMatchPreparation jobSnapshotId={snapshot.id} title={snapshot.title} employerName={snapshot.employerName} providerDescription={snapshot.providerDescription} descriptionAvailability={snapshot.descriptionAvailability} profileId={data.selectedProfile?.profileId} profiles={data.profiles} usage={data.usage} onClose={() => setMatchOpen(false)} />}</main>;
}