'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import type { NormalisedJob, ProviderCount } from '@/shared/types/job';
type Track = { profileId: string; label: string; isDefault: boolean; targetRoleTitle: string; targetOccupation: string; targetIndustry: string; targetSeniority: string };
type SearchOverride = { query?: string; location?: string; profileId?: string };
export function useJobs() {
  const [query, setQuery] = useState(''); const [location, setLocation] = useState(''); const [source, setSource] = useState('all'); const [contractType, setContractType] = useState('all'); const [salaryMin, setSalaryMin] = useState(''); const [sponsorshipFilter, setSponsorshipFilter] = useState('all'); const [experienceLevel, setExperienceLevel] = useState('all'); const [remoteType, setRemoteType] = useState('all'); const [postedWithinDays, setPostedWithinDays] = useState(''); const [sortBy, setSortBy] = useState('relevance');
  const [jobs, setJobs] = useState<NormalisedJob[]>([]); const [isLoading, setIsLoading] = useState(false); const [hasSearched, setHasSearched] = useState(false); const [initialising, setInitialising] = useState(true); const [profiles, setProfiles] = useState<Track[]>([]); const [selectedProfile, setSelectedProfile] = useState<Track | null>(null); const [providerCounts, setProviderCounts] = useState<ProviderCount[]>([]); const [sessionId, setSessionId] = useState<string | null>(null); const [hasMore, setHasMore] = useState(false); const [partialMessage, setPartialMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const searchRef = useRef<AbortController | null>(null);
  const searchJobs = useCallback(async (loadMore = false, override: SearchOverride = {}) => {
    const activeQuery = override.query ?? query; const activeLocation = override.location ?? location; if (!activeQuery.trim()) return;
    searchRef.current?.abort(); const controller = new AbortController(); searchRef.current = controller; setIsLoading(true); setError(null); setHasSearched(true);
    try { const params = new URLSearchParams({ query: activeQuery.trim(), location: activeLocation.trim(), source, contractType, perPage: '15', sponsorship: sponsorshipFilter, experience: experienceLevel, remoteType, sortBy }); if (salaryMin) params.set('salaryMin', salaryMin); if (postedWithinDays) params.set('postedWithinDays', postedWithinDays); if (loadMore && sessionId) params.set('sessionId', sessionId); const response = await fetch(`/api/jobs?${params}`, { signal: controller.signal }); if (!response.ok) throw new Error('Unable to search job sources right now.'); const data = await response.json(); const incoming = data.jobs as NormalisedJob[]; setSessionId(data.sessionId); setProviderCounts(data.meta?.providerCounts ?? []); setPartialMessage(data.meta?.message ?? null); setHasMore(incoming.length === 15); setJobs((previous) => loadMore ? [...previous, ...incoming.filter((job) => !previous.some((existing) => existing.canonicalJobId === job.canonicalJobId))] : incoming); if (!loadMore) window.history.replaceState(null, '', `/jobs?${params}`); } catch (caught) { if ((caught as Error).name !== 'AbortError') { setError(caught instanceof Error ? caught.message : 'Unable to search jobs.'); if (!loadMore) setJobs([]); } } finally { if (!controller.signal.aborted) setIsLoading(false); }
  }, [query, location, source, contractType, salaryMin, sponsorshipFilter, experienceLevel, remoteType, postedWithinDays, sortBy, sessionId]);
  useEffect(() => { (async () => { try { const response = await fetch('/api/jobs/bootstrap'); const data = await response.json(); const track = data.selectedProfile as Track | null; setProfiles(data.profiles ?? []); setSelectedProfile(track); const initial = new URLSearchParams(window.location.search); const urlQuery = initial.get('query'); const nextQuery = urlQuery || data.defaultSearch.query; const nextLocation = initial.get('location') ?? data.defaultSearch.location; setQuery(nextQuery); setLocation(nextLocation); await searchJobs(false, { query: nextQuery, location: nextLocation, profileId: track?.profileId }); } catch { setError('Unable to prepare your Job Board search.'); } finally { setInitialising(false); } })(); }, []);
  const selectProfile = useCallback((profileId: string) => { const track = profiles.find((profile) => profile.profileId === profileId) ?? null; if (!track) return; setSelectedProfile(track); setQuery(track.targetRoleTitle || track.targetOccupation || track.targetIndustry || 'jobs'); setSessionId(null); searchJobs(false, { query: track.targetRoleTitle || track.targetOccupation || track.targetIndustry || 'jobs', profileId }); }, [profiles, searchJobs]);
  return { query, setQuery, location, setLocation, source, setSource, contractType, setContractType, salaryMin, setSalaryMin, sponsorshipFilter, setSponsorshipFilter, experienceLevel, setExperienceLevel, remoteType, setRemoteType, postedWithinDays, setPostedWithinDays, sortBy, setSortBy, jobs, isLoading, hasSearched, initialising, profiles, selectedProfile, selectProfile, providerCounts, error, hasMore, partialMessage, searchJobs };
}